import { Transform, Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  ArrayMaxSize,
  IsArray,
  IsBoolean,
  IsInt,
  IsIn,
  IsObject,
  IsOptional,
  IsString,
  MaxLength,
  Min,
  ValidateNested,
} from 'class-validator';
import { TranslationDto } from '../../localization/translation.dto';
import { ELITE_PERK_CODES } from '../elite-program.constants';

const trim = ({ value }: { value: unknown }): unknown =>
  typeof value === 'string' ? value.trim() : value;

export class EliteTranslationDto extends TranslationDto {
  @IsString()
  @Transform(trim)
  @MaxLength(120)
  declare name: string;

  @IsOptional()
  @IsString()
  @Transform(trim)
  @MaxLength(500)
  declare description?: string;
}

export class EliteBenefitTranslationDto extends EliteTranslationDto {
  @ApiPropertyOptional({ example: '10%' })
  @IsOptional()
  @IsString()
  @MaxLength(120)
  displayValue?: string;
}

export class EliteBenefitInputDto {
  @ApiProperty({ enum: ELITE_PERK_CODES, example: 'tier_commission_policy' })
  @IsString()
  @IsIn(ELITE_PERK_CODES)
  @MaxLength(64)
  code!: string;

  @ApiProperty({ example: 'Reduced Platform Fee' })
  @IsString()
  @MaxLength(120)
  name!: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(500)
  description?: string;

  @ApiPropertyOptional({ example: '10%' })
  @IsOptional()
  @IsString()
  @MaxLength(120)
  displayValue?: string;

  @ApiPropertyOptional({
    type: Object,
    description:
      'Optional presentation metadata. Enforcement metadata is generated by the backend from the supported perk catalog and cannot override the perk effect.',
  })
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown>;

  @ApiPropertyOptional({ default: true })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean = true;

  @ApiPropertyOptional({ default: 0 })
  @IsOptional()
  @IsInt()
  @Min(0)
  sortOrder?: number = 0;

  @ApiPropertyOptional({ type: [EliteBenefitTranslationDto] })
  @IsOptional()
  @IsArray()
  @ArrayMaxSize(20)
  @ValidateNested({ each: true })
  @Type(() => EliteBenefitTranslationDto)
  translations?: EliteBenefitTranslationDto[];
}

export class ReplaceEliteBenefitsDto {
  @ApiProperty({ type: [EliteBenefitInputDto] })
  @IsArray()
  @ArrayMaxSize(30)
  @ValidateNested({ each: true })
  @Type(() => EliteBenefitInputDto)
  benefits!: EliteBenefitInputDto[];
}
